package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTporganization<M extends BaseTporganization<M>> extends Model<M> implements IBean {

	public M setOrgId(java.lang.Integer orgId) {
		set("Org_Id", orgId);
		return (M)this;
	}
	
	public java.lang.Integer getOrgId() {
		return getInt("Org_Id");
	}

	public M setParentCode(java.lang.String ParentCode) {
		set("ParentCode", ParentCode);
		return (M)this;
	}
	
	public java.lang.String getParentCode() {
		return getStr("ParentCode");
	}

	public M setName(java.lang.String Name) {
		set("Name", Name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("Name");
	}

	public M setCode(java.lang.String Code) {
		set("Code", Code);
		return (M)this;
	}
	
	public java.lang.String getCode() {
		return getStr("Code");
	}

	public M setOrgType(java.lang.String orgType) {
		set("Org_Type", orgType);
		return (M)this;
	}
	
	public java.lang.String getOrgType() {
		return getStr("Org_Type");
	}

	public M setStatus(java.lang.Integer Status) {
		set("Status", Status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("Status");
	}

	public M setSortOrder(java.lang.Integer sortOrder) {
		set("Sort_order", sortOrder);
		return (M)this;
	}
	
	public java.lang.Integer getSortOrder() {
		return getInt("Sort_order");
	}

	public M setIsParent(java.lang.Integer isParent) {
		set("Is_parent", isParent);
		return (M)this;
	}
	
	public java.lang.Integer getIsParent() {
		return getInt("Is_parent");
	}

	public M setRemark(java.lang.String Remark) {
		set("Remark", Remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("Remark");
	}

	public M setMenderId(java.lang.String menderId) {
		set("Mender_Id", menderId);
		return (M)this;
	}
	
	public java.lang.String getMenderId() {
		return getStr("Mender_Id");
	}

	public M setModifyTime(java.util.Date ModifyTime) {
		set("ModifyTime", ModifyTime);
		return (M)this;
	}
	
	public java.util.Date getModifyTime() {
		return get("ModifyTime");
	}

	public M setCreatorId(java.lang.String creatorId) {
		set("Creator_Id", creatorId);
		return (M)this;
	}
	
	public java.lang.String getCreatorId() {
		return getStr("Creator_Id");
	}

	public M setCreateTime(java.util.Date CreateTime) {
		set("CreateTime", CreateTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("CreateTime");
	}

}
