package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTplocalization<M extends BaseTplocalization<M>> extends Model<M> implements IBean {

	public M setOrgId(java.lang.Integer orgId) {
		set("Org_Id", orgId);
		return (M)this;
	}
	
	public java.lang.Integer getOrgId() {
		return getInt("Org_Id");
	}

	public M setParentCode(java.lang.String ParentCode) {
		set("ParentCode", ParentCode);
		return (M)this;
	}
	
	public java.lang.String getParentCode() {
		return getStr("ParentCode");
	}

	public M setName(java.lang.String Name) {
		set("Name", Name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("Name");
	}

}
