package com.pointlion.sys.mvc.common.model.base;

import java.util.List;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;
import com.pointlion.sys.mvc.common.model.SysOrg;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysOrg<M extends BaseSysOrg<M>> extends Model<M> implements IBean {
	private List<SysOrg> children;
	
	public List<SysOrg> getChildren() {
		return children;
	}
	public void setChildren(List<SysOrg> children) {
		this.children = children;
	}
	
	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setAreaCode(java.lang.Long areaCode) {
		set("areaCode", areaCode);
	}

	public java.lang.Long getAreaCode() {
		return get("areaCode");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}

	public java.lang.String getImage() {
		return get("image");
	}

	public void setIsparent(java.lang.String isparent) {
		set("isparent", isparent);
	}

	public java.lang.String getIsparent() {
		return get("isparent");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSort(java.lang.Long sort) {
		set("sort", sort);
	}

	public java.lang.Long getSort() {
		return get("sort");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

	public void setOperate(java.lang.String operate) {
		set("operate", operate);
	}

	public java.lang.String getOperate() {
		return get("operate");
	}
	
	public void setEvaluate(java.lang.String evaluate){
		set("evaluate", evaluate);
	}
	
	public java.lang.String getEvaluate() {
		return get("evaluate");
	}

	public void setDescrible(java.lang.String describle) {
		set("describle", describle);
	}

	public java.lang.String getDescrible() {
		return getStr("describle");
	}
	
	public void setMarkTime(java.lang.String marktime) {
		set("marktime", marktime);
	}

	public java.lang.String getMarkTime() {
		return getStr("marktime");
	}
	
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}

	public java.lang.String getUserid() {
		return get("userid");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}
	
	public void setParentname(java.lang.String parentname) {
		set("parentname", parentname);
	}
	
	public java.lang.String getParentname() {
		return get("parentname");
	}
	
	public void setQxusername(java.lang.String qxusername) {
		set("qxusername", qxusername);
	}
	
	public java.lang.String getQxusername() {
		return get("qxusername");
	}
	
	public void setZjName(java.lang.String zjname) {
		set("zjname", zjname);
	}

	public java.lang.String getZjName() {
		return getStr("zjname");
	}
	
	public void setZjpfbz(java.lang.String zjpfbz) {
		set("zjpfbz", zjpfbz);
	}
	
	public java.lang.String getZjpfbz() {
		return get("zjpfbz");
	}
	
	public void setZjpfms(java.lang.String zjpfms) {
		set("zjpfms", zjpfms);
	}
	
	public java.lang.String getZjpfms() {
		return get("zjpfms");
	}
	
	public void setZjTime(java.lang.String zjtime) {
		set("zjtime", zjtime);
	}

	public java.lang.String getZjTime() {
		return getStr("zjtime");
	}
	
}
