package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseResource<M extends BaseResource<M>> extends Model<M> implements IBean {

	public M setRid(java.lang.String rid) {
		set("rid", rid);
		return (M)this;
	}
	
	public java.lang.String getRid() {
		return getStr("rid");
	}

	public M setRname(java.lang.String rname) {
		set("rname", rname);
		return (M)this;
	}
	
	public java.lang.String getRname() {
		return getStr("rname");
	}

	public M setUploadPath(java.lang.String uploadPath) {
		set("uploadPath", uploadPath);
		return (M)this;
	}
	
	public java.lang.String getUploadPath() {
		return getStr("uploadPath");
	}

	public M setSuffix(java.lang.String suffix) {
		set("suffix", suffix);
		return (M)this;
	}
	
	public java.lang.String getSuffix() {
		return getStr("suffix");
	}

	public M setUploader(java.lang.String uploader) {
		set("uploader", uploader);
		return (M)this;
	}
	
	public java.lang.String getUploader() {
		return getStr("uploader");
	}

	public M setUploadArea(java.lang.String uploadArea) {
		set("uploadArea", uploadArea);
		return (M)this;
	}
	
	public java.lang.String getUploadArea() {
		return getStr("uploadArea");
	}

	public M setAreaCode(java.lang.String areaCode) {
		set("areaCode", areaCode);
		return (M)this;
	}
	
	public java.lang.String getAreaCode() {
		return getStr("areaCode");
	}

	public M setMenderId(java.lang.String menderId) {
		set("mender_Id", menderId);
		return (M)this;
	}
	
	public java.lang.String getMenderId() {
		return getStr("mender_Id");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("modifyTime", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("modifyTime");
	}

	public M setCreatorId(java.lang.String creatorId) {
		set("creator_Id", creatorId);
		return (M)this;
	}
	
	public java.lang.String getCreatorId() {
		return getStr("creator_Id");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("createTime");
	}

}
