package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({ "serial", "unchecked" })
public abstract class BaseTopic<M extends BaseTopic<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M) this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}
	
	public M setTypeId(java.lang.String typeid) {
		set("typeid", typeid);
		return (M) this;
	}

	public java.lang.String getTypeId() {
		return getStr("typeid");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M) this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setDescrible(java.lang.String describle) {
		set("describle", describle);
		return (M) this;
	}

	public java.lang.String getDescrible() {
		return getStr("describle");
	}

	public M setUserId(java.lang.String userid) {
		set("userid", userid);
		return (M) this;
	}

	public java.lang.String getUserId() {
		return getStr("userid");
	}

	public M setCreateTime(java.lang.String createtime) {
		set("createtime", createtime);
		return (M) this;
	}

	public java.lang.String getCreateTime() {
		return getStr("createtime");
	}

	public M setSubmit(java.lang.Integer submit) {
		set("submit", submit);
		return (M) this;
	}

	public java.lang.String getSubmit() {
		return getStr("submit");
	}

	public M setSortValue(java.lang.Integer sortvalue) {
		set("sortvalue", sortvalue);
		return (M) this;
	}

	public java.lang.String getSortValue() {
		return getStr("sortvalue");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M) this;
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setOrgName(java.lang.String orgname) {
		set("orgname", orgname);
		return (M) this;
	}

	public java.lang.String getOrgName() {
		return getStr("orgname");
	}


	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M) this;
	}

	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public M setBeginTime(java.lang.String begintime) {
		set("begintime", begintime);
		return (M) this;
	}

	public java.lang.String getBeginTime() {
		return getStr("begintime");
	}
	
	public M setEndTime(java.lang.String endtime) {
		set("endtime", endtime);
		return (M) this;
	}
	
	public java.lang.String getEndTime() {
		return getStr("endtime");
	}
	
	public M setQxBeginTime(java.lang.String qxbegintime) {
		set("qxbegintime", qxbegintime);
		return (M) this;
	}
	
	public java.lang.String getQxBeginTime() {
		return getStr("qxbegintime");
	}
	
	public M setQxEndTime(java.lang.String qxendtime) {
		set("qxendtime", qxendtime);
		return (M) this;
	}
	
	public java.lang.String getQxEndTime() {
		return getStr("qxendtime");
	}
	
	public M setZjBeginTime(java.lang.String zjbegintime) {
		set("zjbegintime", zjbegintime);
		return (M) this;
	}
	
	public java.lang.String getZjBeginTime() {
		return getStr("zjbegintime");
	}
	
	public M setZjEndTime(java.lang.String zjendtime) {
		set("zjendtime", zjendtime);
		return (M) this;
	}
	
	public java.lang.String getZjEndTime() {
		return getStr("zjendtime");
	}
}
