package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({ "serial", "unchecked" })
public abstract class BaseTopicDelay<M extends BaseTopicDelay<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M) this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setUserId(java.lang.String userid) {
		set("userid", userid);
		return (M) this;
	}

	public java.lang.String getUserId() {
		return getStr("userid");
	}

	public M setCreateTime(java.lang.String createtime) {
		set("createtime", createtime);
		return (M) this;
	}

	public java.lang.String getCreateTime() {
		return getStr("createtime");
	}
	
	public M setYqendTime(java.lang.String yqendtime) {
		set("yqendtime", yqendtime);
		return (M) this;
	}
	
	public java.lang.String getYqendTime() {
		return getStr("yqendtime");
	}

	public M setTopicId(java.lang.String topicid) {
		set("topicid", topicid);
		return (M) this;
	}

	public java.lang.String getTopicId() {
		return getStr("topicid");
	}
	
	public M setQuestionId(java.lang.String questionid) {
		set("questionid", questionid);
		return (M) this;
	}

	public java.lang.String getQuestionId() {
		return getStr("questionid");
	}
	
	public M setStat(java.lang.Integer stat) {
		set("stat", stat);
		return (M) this;
	}
	
	public java.lang.Integer getStat() {
		return getInt("stat");
	}
}
