package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({ "serial", "unchecked" })
public abstract class BaseScore<M extends BaseScore<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M) this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setDescrible(java.lang.String describle) {
		set("describle", describle);
		return (M) this;
	}

	public java.lang.String getDescrible() {
		return getStr("describle");
	}

	public M setCreateTime(java.lang.String createtime) {
		set("createtime", createtime);
		return (M) this;
	}

	public java.lang.String getCreateTime() {
		return getStr("createtime");
	}

	public M setTopicId(java.lang.String topicid) {
		set("topicid", topicid);
		return (M) this;
	}

	public java.lang.String getTopicId() {
		return getStr("topicid");
	}

	public M setUserId(java.lang.String userid) {
		set("userid", userid);
		return (M) this;
	}

	public java.lang.String getUserId() {
		return getStr("userid");
	}

	public M setEvaluate(java.lang.String evaluate) {
		set("evaluate", evaluate);
		return (M) this;
	}
	
	public java.lang.String getEvaluate() {
		return getStr("evaluate");
	}
	
	public M setScore(java.lang.String score) {
		set("score", score);
		return (M) this;
	}

	public java.lang.String getScore() {
		return getStr("score");
	}

	public M setPersonId(java.lang.String personid) {
		set("personid", personid);
		return (M) this;
	}

	public java.lang.String getPersonId() {
		return getStr("personid");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M) this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setUserName(java.lang.String username) {
		set("username", username);
		return (M) this;
	}

	public java.lang.String getUserName() {
		return getStr("username");
	}

	public M setPerson(java.lang.String person) {
		set("person", person);
		return (M) this;
	}

	public java.lang.String getPerson() {
		return getStr("person");
	}

	public M setMarkTime(java.lang.String marktime) {
		set("marktime", marktime);
		return (M) this;
	}

	public java.lang.String getMarkTime() {
		return getStr("marktime");
	}

	public M setOrgName(java.lang.String orgname) {
		set("orgname", orgname);
		return (M) this;
	}

	public java.lang.String getOrgName() {
		return getStr("orgname");
	}

	public M setZjpfbz(java.lang.String zjpfbz) {
		set("zjpfbz", zjpfbz);
		return (M) this;
	}

	public java.lang.String getZjpfbz() {
		return getStr("zjpfbz");
	}

	public M setZjpfms(java.lang.String zjpfms) {
		set("zjpfms", zjpfms);
		return (M) this;
	}

	public java.lang.String getZjpfms() {
		return getStr("zjpfms");
	}

	public M setZjId(java.lang.String zjid) {
		set("zjid", zjid);
		return (M) this;
	}

	public java.lang.String getZjId() {
		return getStr("zjid");
	}

	public M setZjName(java.lang.String zjname) {
		set("zjname", zjname);
		return (M) this;
	}

	public java.lang.String getZjName() {
		return getStr("zjname");
	}

	public M setZjTime(java.lang.String zjtime) {
		set("zjtime", zjtime);
		return (M) this;
	}

	public java.lang.String getZjTime() {
		return getStr("zjtime");
	}
	
	public M setQxBeginTime(java.lang.String qxbegintime) {
		set("qxbegintime", qxbegintime);
		return (M) this;
	}
	
	public java.lang.String getQxBeginTime() {
		return getStr("qxbegintime");
	}
	
	public M setQxEndTime(java.lang.String qxendtime) {
		set("qxendtime", qxendtime);
		return (M) this;
	}
	
	public java.lang.String getQxEndTime() {
		return getStr("qxendtime");
	}
	
	public M setZjBeginTime(java.lang.String zjbegintime) {
		set("zjbegintime", zjbegintime);
		return (M) this;
	}
	
	public java.lang.String getZjBeginTime() {
		return getStr("zjbegintime");
	}
	
	public M setZjEndTime(java.lang.String zjendtime) {
		set("zjendtime", zjendtime);
		return (M) this;
	}
	
	public java.lang.String getZjEndTime() {
		return getStr("zjendtime");
	}
}
