package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminApplog<M extends BaseAdminApplog<M>> extends Model<M> implements IBean {

	public M setLogId(java.lang.String logId) {
		set("Log_Id", logId);
		return (M)this;
	}
	
	public java.lang.String getLogId() {
		return getStr("Log_Id");
	}

	public M setOperator(java.lang.String Operator) {
		set("Operator", Operator);
		return (M)this;
	}
	
	public java.lang.String getOperator() {
		return getStr("Operator");
	}

	public M setOperObject(java.lang.String operObject) {
		set("Oper_Object", operObject);
		return (M)this;
	}
	
	public java.lang.String getOperObject() {
		return getStr("Oper_Object");
	}

	public M setSourceIp(java.lang.String sourceIp) {
		set("Source_Ip", sourceIp);
		return (M)this;
	}
	
	public java.lang.String getSourceIp() {
		return getStr("Source_Ip");
	}

	public M setDestIp(java.lang.String destIp) {
		set("Dest_Ip", destIp);
		return (M)this;
	}
	
	public java.lang.String getDestIp() {
		return getStr("Dest_Ip");
	}

	public M setOperateTime(java.lang.String operateTime) {
		set("Operate_Time", operateTime);
		return (M)this;
	}
	
	public java.lang.String getOperateTime() {
		return getStr("Operate_Time");
	}

}
