package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTDbbackup<M extends BaseTDbbackup<M>> extends Model<M> implements IBean {

	public M setBkId(java.lang.String bkId) {
		set("bkId", bkId);
		return (M)this;
	}
	
	public java.lang.String getBkId() {
		return getStr("bkId");
	}

	public M setBkObject(java.lang.String bkObject) {
		set("bkObject", bkObject);
		return (M)this;
	}
	
	public java.lang.String getBkObject() {
		return getStr("bkObject");
	}

	public M setBkTime(java.lang.String bkTime) {
		set("bkTime", bkTime);
		return (M)this;
	}
	
	public java.lang.String getBkTime() {
		return get("bkTime");
	}

	public M setOperateUser(java.lang.String operateUser) {
		set("operateUser", operateUser);
		return (M)this;
	}
	
	public java.lang.String getOperateUser() {
		return getStr("operateUser");
	}

	public M setStorageLocation(java.lang.String storageLocation) {
		set("storageLocation", storageLocation);
		return (M)this;
	}
	
	public java.lang.String getStorageLocation() {
		return getStr("storageLocation");
	}

	public M setDateSize(java.lang.String dateSize) {
		set("dateSize", dateSize);
		return (M)this;
	}
	
	public java.lang.String getDateSize() {
		return getStr("dateSize");
	}

}
