package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({ "serial", "unchecked" })
public abstract class BaseTopicType<M extends BaseTopicType<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M) this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M) this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M) this;
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public M setSortvalue(java.lang.Integer sortvalue) {
		set("sortvalue", sortvalue);
		return (M) this;
	}
	
	public java.lang.Integer getSortvalue() {
		return getInt("sortvalue");
	}

}
