package com.pointlion.sys.mvc.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTpsource<M extends BaseTpsource<M>> extends Model<M> implements IBean {

	public M setTpId(java.lang.String tpId) {
		set("TP_Id", tpId);
		return (M)this;
	}
	
	public java.lang.String getTpId() {
		return getStr("TP_Id");
	}

	public M setTPName(java.lang.String TPName) {
		set("TPName", TPName);
		return (M)this;
	}
	
	public java.lang.String getTPName() {
		return getStr("TPName");
	}

	public M setTpcCode(java.lang.Integer tpcCode) {
		set("TPC_Code", tpcCode);
		return (M)this;
	}
	
	public java.lang.Integer getTpcCode() {
		return getInt("TPC_Code");
	}

	public M setTpqCode(java.lang.Integer tpqCode) {
		set("TPQ_Code", tpqCode);
		return (M)this;
	}
	
	public java.lang.Integer getTpqCode() {
		return getInt("TPQ_Code");
	}

	public M setTppCode(java.lang.Integer tppCode) {
		set("TPP_Code", tppCode);
		return (M)this;
	}
	
	public java.lang.Integer getTppCode() {
		return getInt("TPP_Code");
	}

	public M setOrgId(java.lang.Integer orgId) {
		set("Org_Id", orgId);
		return (M)this;
	}
	
	public java.lang.Integer getOrgId() {
		return getInt("Org_Id");
	}

	public M setStatusCode(java.lang.Integer statusCode) {
		set("Status_Code", statusCode);
		return (M)this;
	}
	
	public java.lang.Integer getStatusCode() {
		return getInt("Status_Code");
	}

	public M setSex(java.lang.String Sex) {
		set("Sex", Sex);
		return (M)this;
	}
	
	public java.lang.String getSex() {
		return getStr("Sex");
	}
	
	public M setType(java.lang.String Type) {
		set("type", Type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setAge(java.lang.String Age) {
		set("Age", Age);
		return (M)this;
	}
	
	public java.lang.String getAge() {
		return getStr("Age");
	}

	public M setIdentyId(java.lang.String identyId) {
		set("Identy_Id", identyId);
		return (M)this;
	}
	
	public java.lang.String getIdentyId() {
		return getStr("Identy_Id");
	}

	public M setTel(java.lang.String Tel) {
		set("Tel", Tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("Tel");
	}

	public M setTpAdd(java.lang.String tpAdd) {
		set("TP_Add", tpAdd);
		return (M)this;
	}
	
	public java.lang.String getTpAdd() {
		return getStr("TP_Add");
	}

	public M setEmail(java.lang.String Email) {
		set("Email", Email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("Email");
	}

	public M setProfession(java.lang.String Profession) {
		set("Profession", Profession);
		return (M)this;
	}
	
	public java.lang.String getProfession() {
		return getStr("Profession");
	}

	public M setIconUrl(java.lang.String iconUrl) {
		set("Icon_Url", iconUrl);
		return (M)this;
	}
	
	public java.lang.String getIconUrl() {
		return getStr("Icon_Url");
	}

	public M setPosition(java.lang.String Position) {
		set("Position", Position);
		return (M)this;
	}
	
	public java.lang.String getPosition() {
		return getStr("Position");
	}

	public M setGZjf(java.lang.String GZjf) {
		set("GZjf", GZjf);
		return (M)this;
	}
	
	public java.lang.String getGZjf() {
		return getStr("GZjf");
	}

	public M setWorkAge(java.lang.Integer workAge) {
		set("Work_Age", workAge);
		return (M)this;
	}
	
	public java.lang.Integer getWorkAge() {
		return getInt("Work_Age");
	}

	public M setBZlb(java.lang.String BZlb) {
		set("BZlb", BZlb);
		return (M)this;
	}
	
	public java.lang.String getBZlb() {
		return getStr("BZlb");
	}
	
	public M setTeacherIntroduction(java.lang.String TeacherIntroduction) {
		set("TeacherIntroduction", TeacherIntroduction);
		return (M)this;
	}
	
	public java.lang.String getTeacherIntroduction() {
		return getStr("TeacherIntroduction");
	}

	public M setOpus(java.lang.String Opus) {
		set("Opus", Opus);
		return (M)this;
	}
	
	public java.lang.String getOpus() {
		return getStr("Opus");
	}

	public M setVilage(java.lang.String Vilage) {
		set("Vilage", Vilage);
		return (M)this;
	}
	
	public java.lang.String getVilage() {
		return getStr("Vilage");
	}

	public M setVilPeo(java.lang.String vilPeo) {
		set("Vil_Peo", vilPeo);
		return (M)this;
	}
	
	public java.lang.String getVilPeo() {
		return getStr("Vil_Peo");
	}

	public M setTown(java.lang.String Town) {
		set("Town", Town);
		return (M)this;
	}
	
	public java.lang.String getTown() {
		return getStr("Town");
	}

	public M setTowPeo(java.lang.String towPeo) {
		set("Tow_Peo", towPeo);
		return (M)this;
	}
	
	public java.lang.String getTowPeo() {
		return getStr("Tow_Peo");
	}

	public M setCountry(java.lang.String Country) {
		set("Country", Country);
		return (M)this;
	}
	
	public java.lang.String getCountry() {
		return getStr("Country");
	}

	public M setCouPeo(java.lang.String couPeo) {
		set("Cou_Peo", couPeo);
		return (M)this;
	}
	
	public java.lang.String getCouPeo() {
		return getStr("Cou_Peo");
	}

	public M setCity(java.lang.String City) {
		set("City", City);
		return (M)this;
	}
	
	public java.lang.String getCity() {
		return getStr("City");
	}

	public M setCitPeo(java.lang.String citPeo) {
		set("Cit_Peo", citPeo);
		return (M)this;
	}
	
	public java.lang.String getCitPeo() {
		return getStr("Cit_Peo");
	}

	public M setSave(java.lang.String Save) {
		set("Save", Save);
		return (M)this;
	}
	
	public java.lang.String getSave() {
		return getStr("Save");
	}

	public M setSavPeo(java.lang.String savPeo) {
		set("Sav_Peo", savPeo);
		return (M)this;
	}
	
	public java.lang.String getSavPeo() {
		return getStr("Sav_Peo");
	}

	public M setMenderId(java.lang.String menderId) {
		set("Mender_Id", menderId);
		return (M)this;
	}
	
	public java.lang.String getMenderId() {
		return getStr("Mender_Id");
	}

	//时间都改成String类型
	public M setModifyTime(java.lang.String ModifyTime) {
		set("ModifyTime", ModifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return get("ModifyTime");
	}

	public M setCreatorId(java.lang.String creatorId) {
		set("Creator_Id", creatorId);
		return (M)this;
	}
	
	public java.lang.String getCreatorId() {
		return getStr("Creator_Id");
	}
	
	public M setMunicipalLevel(java.lang.String provincialLevel) {
		set("municipallevel", provincialLevel);
		return (M)this;
	}
	
	public java.lang.String getMunicipalLevel() {
		return getStr("municipallevel");
	}
	
	public M setCountyLevel(java.lang.String countyLevel) {
		set("countylevel", countyLevel);
		return (M)this;
	}
	
	public java.lang.String getCountyLevel() {
		return getStr("countylevel");
	}

	public M setCreateTime(java.lang.String CreateTime) {
		set("CreateTime", CreateTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return get("CreateTime");
	}

}
