package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTPublicService<M extends BaseTPublicService<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setTemplateData(java.lang.String templateData) {
		set("templateData", templateData);
		return (M)this;
	}
	
	public java.lang.String getTemplateData() {
		return getStr("templateData");
	}

	public M setOtherContext(java.lang.String otherContext) {
		set("otherContext", otherContext);
		return (M)this;
	}
	
	public java.lang.String getOtherContext() {
		return getStr("otherContext");
	}

	public M setType(java.lang.Integer Type) {
		set("type", Type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public M setCreateTimet(java.lang.String createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("createTime");
	}
	
	public M setAreaCode(java.lang.Long areaCode) {
		set("areaCode", areaCode);
		return (M)this;
	}
	
	public java.lang.Long getAreaCode() {
		return get("areaCode");
	}
	
	public M setLeavl(java.lang.String leavl) {
		set("leavl", leavl);
		return (M)this;
	}
	
	public java.lang.String getLeavl() {
		return getStr("leavl");
	}
	
	
	public M setUploader(java.lang.String uploader) {
		set("uploader", uploader);
		return (M)this;
	}
	
	public java.lang.String getUploader() {
		return getStr("uploader");
	}

	public M setIsPass(java.lang.String isPass) {
		set("isPass", isPass);
		return (M)this;
	}
	
	public java.lang.String getIsPass() {
		return getStr("isPass");
	}
}
