package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSuffix<M extends BaseSuffix<M>> extends Model<M> implements IBean {

	public M setSid(java.lang.String sid) {
		set("sid", sid);
		return (M)this;
	}
	
	public java.lang.String getSid() {
		return getStr("sid");
	}

	public M setSuffix(java.lang.String suffix) {
		set("suffix", suffix);
		return (M)this;
	}
	
	public java.lang.String getSuffix() {
		return getStr("suffix");
	}

	public M setMenderId(java.lang.String menderId) {
		set("mender_Id", menderId);
		return (M)this;
	}
	
	public java.lang.String getMenderId() {
		return getStr("mender_Id");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("modifyTime", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("modifyTime");
	}

	public M setCreatorId(java.lang.String creatorId) {
		set("creator_Id", creatorId);
		return (M)this;
	}
	
	public java.lang.String getCreatorId() {
		return getStr("creator_Id");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("createTime");
	}

}
