package com.pointlion.sys.mvc.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAnswerExcel<M extends BaseAnswerExcel<M>> extends Model<M> implements IBean {

	public java.lang.String getId() {
		return getStr("id");
	}
	
	public M setId(java.lang.String id) {
		set("id", id);
		return (M) this;
	}
	
	public M setCreateTime(java.lang.String createtime) {
		set("createtime", createtime);
		return (M) this;
	}

	public java.lang.String getCreateTime() {
		return getStr("createtime");
	}

	public java.lang.String getQuestionId() {
		return getStr("questionid");
	}
	
	public M setQuestionId(java.lang.String questionid) {
		set("questionid", questionid);
		return (M) this;
	}
	
	public java.lang.String getAnswerId() {
		return getStr("answerid");
	}
	
	public M setAnswerId(java.lang.String answerid) {
		set("answerid", answerid);
		return (M) this;
	}
	
	public java.lang.String getPersonId() {
		return getStr("personid");
	}
	
	public M setPersonId(java.lang.String personid) {
		set("personid", personid);
		return (M) this;
	}
	
	public java.lang.String getTarget() {
		return getStr("target");
	}
	public M setTarget(java.lang.String target) {
		set("target", target);
		return (M) this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M) this;
	}
	
	public java.lang.String getAnswerval() {
		return getStr("answerval");
	}
	
	public M setAnswerval(java.lang.String answerval) {
		set("answerval", answerval);
		return (M) this;
	}
	
	public java.lang.String getAnswervaljson() {
		return getStr("answervaljson");
	}
	
	public M setAnswervaljson(java.lang.String answervaljson) {
		set("answervaljson", answervaljson);
		return (M) this;
	}
	
	public M setFileId(java.lang.String fileid) {
		set("fileid", fileid);
		return (M)this;
	}
	
	public java.lang.String getFileId() {
		return getStr("fileid");
	}
	
	public M setSortvalue(java.lang.Integer sortvalue) {
		set("sortvalue", sortvalue);
		return (M)this;
	}
	
	public java.lang.Integer getSortvalue() {
		return getInt("sortvalue");
	}
}
