package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTCustomFieldTemplate<M extends BaseTCustomFieldTemplate<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setFieldName(java.lang.String fieldName) {
		set("fieldName", fieldName);
		return (M)this;
	}
	
	public java.lang.String getFieldName() {
		return getStr("fieldName");
	}
	
	public M setDescrible(java.lang.String describle) {
		set("describle", describle);
		return (M)this;
	}
	
	public java.lang.String getDescrible() {
		return getStr("describle");
	}

	public M setContext(java.lang.String context) {
		set("context", context);
		return (M)this;
	}
	
	public java.lang.String getContext() {
		return getStr("context");
	}

}
