package com.pointlion.sys.mvc.common.model;

import java.net.InetAddress;
import java.net.UnknownHostException;

import javax.servlet.http.HttpServletRequest;

import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.tx.Tx;
import com.pointlion.sys.mvc.common.model.base.BaseAdminApplog;
import com.pointlion.sys.mvc.common.utils.DateUtil;
import com.pointlion.sys.mvc.common.utils.UuidUtil;
import com.pointlion.sys.plugin.shiro.ShiroKit;
import com.pointlion.sys.plugin.shiro.ext.SimpleUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminApplog extends BaseAdminApplog<AdminApplog> {
public static final AdminApplog dao = new AdminApplog();
	
	/***
	 * 根据主键查询
	 */
	public AdminApplog getById(String id){
		return AdminApplog.dao.findById(id);
	}
	
	/***
	 * 根据主键获取用户名
	 * @param userid
	 * @return
	 */
	/*public String getUsername(String userid){
		return getById(userid).getUsername(getOperator());
	}*/
	
	/***
	 * 删除
	 * @param ids
	 */
	@Before(Tx.class)
	public void deleteByIds(String ids){
		String idarr[] = ids.split(",");
    	for(String logid : idarr){
    		AdminApplog menu = AdminApplog.dao.getById(logid);
			if(menu!=null){
				menu.delete();//删除角色

			}
    	}
	}
	static String userId = ShiroKit.getUserId();//用户主键
	static SysUser user = SysUser.dao.getById(userId);//用户对象
	public String getIpAddr(HttpServletRequest request) {
		String ipAddress = request.getHeader("x-forwarded-for");  
        if(ipAddress == null || ipAddress.length() == 0 || "unknown".equalsIgnoreCase(ipAddress)) {  
            ipAddress = request.getHeader("Proxy-Client-IP");  
        }  
        if(ipAddress == null || ipAddress.length() == 0 || "unknown".equalsIgnoreCase(ipAddress)) {  
            ipAddress = request.getHeader("WL-Proxy-Client-IP");  
        }  
        if(ipAddress == null || ipAddress.length() == 0 || "unknown".equalsIgnoreCase(ipAddress)) {  
            ipAddress = request.getRemoteAddr();  
            if(ipAddress.equals("127.0.0.1") || ipAddress.equals("0:0:0:0:0:0:0:1")){  
                //根据网卡取本机配置的IP  
                InetAddress inet=null;  
                try {  
                    inet = InetAddress.getLocalHost();  
                } catch (UnknownHostException e) {  
                    e.printStackTrace();  
                }  
                ipAddress= inet.getHostAddress();  
            }  
        }  
        //对于通过多个代理的情况，第一个IP为客户端真实IP,多个IP按照','分割  
        if(ipAddress!=null && ipAddress.length()>15){ //"***.***.***.***".length() = 15  
            if(ipAddress.indexOf(",")>0){  
                ipAddress = ipAddress.substring(0,ipAddress.indexOf(","));  
            }  
        }  
        return ipAddress;   
		}
	public static void set(String op,String Ip,String ServerIp)
	{
	
		AdminApplog log = new AdminApplog();
		log.setLogId(UuidUtil.getUUID());
		log.setOperator(user.getName());
		log.setSourceIp(Ip);
		log.setDestIp(ServerIp);
		log.setOperateTime(DateUtil.getTime());
		log.setOperObject(op);
		log.save();
	}
	
	/***
	 * 查询应用日志分页
	 * @param curr
	 * @param pagesize
	 * @return
	 */
	public Page<AdminApplog> getAppLogPage(Integer curr , Integer pagesize){
		return AdminApplog.dao.paginate(curr, pagesize, "select * ", " from t_admin_applog");
		
	}
	
}
