package com.pointlion.sys.mvc.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.pointlion.sys.mvc.common.model.base.BaseAnswerExcel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AnswerExcel extends BaseAnswerExcel<AnswerExcel> {
	public static final AnswerExcel dao = new AnswerExcel();
	
	
	public void deleteByFileid(String fileid){
		Db.update("delete from t_answer_excel where fileid = '"+fileid+"' ");
	}
	public void deleteByAnswerid(String answerid){
		Db.update("delete from t_answer_excel where answerid = '"+answerid+"' ");
	}
}
