package com.pointlion.sys.mvc.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.pointlion.sys.mvc.common.model.base.BaseResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resource extends BaseResource<Resource> {
	public final static  Resource dao  = new  Resource();

	public Page<Resource> getPage(Integer currPage, Integer pageSize, String date, String suffix, String area, String uploader, String keyWord, String code) {

		String sqlExceptSelect = "from t_resource where 1=1";
		if(date!=""){
			sqlExceptSelect+=" and createTime = '"+date+"'";
		}
		if(suffix!=""){
			sqlExceptSelect += " and suffix = '"+suffix+"'";
		}
		if(area!=""){
			sqlExceptSelect += " and uploadArea = '"+area+"'";
		}
		if(uploader!=""){
			sqlExceptSelect += " and uploader = '"+uploader+"'";
		}
		if(keyWord!=""){
			sqlExceptSelect += " and rname like '%"+keyWord+"%'";
		}
		if(code!=""){
			sqlExceptSelect += " and areaCode like '"+code+"%'";
		}
				
		Page<Resource> paginate = dao.paginate(currPage, pageSize, "select * ", sqlExceptSelect);
		
		
		
		return paginate;
	}
	
	
	
	
}
