package com.pointlion.sys.mvc.common.model;

import java.util.List;

import com.pointlion.sys.mvc.common.model.base.BaseSuffix;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Suffix extends BaseSuffix<Suffix> {
	
	public final static Suffix dao = new Suffix();

	public boolean isExit(String suffix) {

		Suffix findFirst = dao.findFirst("select * from t_suffix where suffix = ?",suffix);
		if(findFirst!=null){
			return false;
		}
		else{
			return true;
		}
	}

	public List<Suffix> findAll() {

		List<Suffix> find = dao.find("select * from t_suffix");
		return find;
	}
	
	
	
	
}
