package com.pointlion.sys.mvc.common.model;

import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.tx.Tx;
import com.pointlion.sys.mvc.common.model.base.BaseSysApplog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysApplog extends BaseSysApplog<SysApplog> {
	public static final SysApplog dao = new SysApplog();
	
	/***
	 * 根据主键查询
	 */
	public SysApplog getById(String id){
		return SysApplog.dao.findById(id);
	}
	
	/***
	 * 删除
	 * @param ids
	 */
	@Before(Tx.class)
	public void deleteByIds(String ids){
		String idarr[] = ids.split(",");
    	for(String logid : idarr){
    		SysApplog menu = SysApplog.dao.getById(logid);
			if(menu!=null){
				menu.delete();//删除角色

			}
    	}
	}

	/***
	 * 查询应用日志分页
	 * @param curr
	 * @param pagesize
	 * @return
	 */
	public Page<SysApplog> getAppLogPage(Integer curr , Integer pagesize){
		return SysApplog.dao.paginate(curr, pagesize, "select * ", " from sys_applog");
		
	}
	
}
