package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseSysUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserRole extends BaseSysUserRole<SysUserRole> {
	public static final SysUserRole dao = new SysUserRole();
	
	public SysUserRole findByUserId(String userId) {
		
		SysUserRole sysUserRole = dao.findFirst("select * from sys_user_role where user_id = ?",userId);
		
		return sysUserRole;
	}
}
