package com.pointlion.sys.mvc.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.pointlion.sys.mvc.common.model.base.BaseTDbbackup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TDbbackup extends BaseTDbbackup<TDbbackup> {
	public static final TDbbackup dao = new TDbbackup().dao();
	
	
	/***
	 * 获取分页
	 */
	public Page<TDbbackup> getPage(int pnum,int psize){
		return TDbbackup.dao.paginate(pnum, psize, "select * ", " from swq_t_dbbackup");
	}
}
