package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseTpauditstatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tpauditstatus extends BaseTpauditstatus<Tpauditstatus> {
	
}
