package com.pointlion.sys.mvc.common.model;

import java.util.List;

import com.pointlion.sys.mvc.common.model.base.BaseTpclassify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tpclassify extends BaseTpclassify<Tpclassify> {
public static final Tpclassify dao = new Tpclassify();
	
	public Tpclassify getById(String id){
		return Tpclassify.dao.findById(id);
	}
	
	public List<Tpclassify> getlist()
	{
	return Tpclassify.dao.find("select * from t_tpclassify");		
	}
}
