package com.pointlion.sys.mvc.common.model;

import java.util.List;

import com.pointlion.sys.mvc.common.model.base.BaseTplocalization;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tplocalization extends BaseTplocalization<Tplocalization> {
	public static final Tplocalization dao = new Tplocalization();
	
	public List<Tplocalization> findTop(){
		
		List<Tplocalization> tpo = dao.find("select * from t_tplocalization where ParentCode ='0'");
		return tpo;
	}

	public List<Tplocalization> findChild(Integer orgId) {
		
		List<Tplocalization> tpoChild = dao.find("select * from t_tplocalization where ParentCode =?", orgId);
		return tpoChild;
	}
	
	public String getName(String tplId){
			Tplocalization tplocalization = dao.findById(tplId);
			return tplocalization.getName();
	}
}
