package com.pointlion.sys.mvc.common.model;

import java.util.List;

import com.pointlion.sys.mvc.common.model.base.BaseTppolitical;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tppolitical extends BaseTppolitical<Tppolitical> {
public static final  Tppolitical dao = new Tppolitical();
	
	public List<Tppolitical> getList(){
			List<Tppolitical> tpp = dao.find("select * from t_tppolitical");
			return tpp;
	}
}
