package com.pointlion.sys.mvc.common.model;

import java.util.List;

import com.pointlion.sys.mvc.common.model.base.BaseTpqualifications;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tpqualifications extends BaseTpqualifications<Tpqualifications> {
public static final Tpqualifications dao = new Tpqualifications();
	
	public List<Tpqualifications> getlist(){
		return dao.find("select * from t_tpqualifications");
	}
}
