package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseTPsCft;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TPsCft extends BaseTPsCft<TPsCft> {
	
}
