package com.pointlion.sys.mvc.common.model;

import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.tx.Tx;
import com.pointlion.sys.mvc.common.model.base.BaseTPublicService;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TPublicService extends BaseTPublicService<TPublicService> {
	public final static TPublicService dao = new TPublicService();
	
	public Page<TPublicService> getImPage(Integer currPage, Integer pageSize, String state, String createTime, String keyWord,String code) {
		if(createTime==""){
			if(state==""){
				return TPublicService.dao.paginate(currPage, pageSize, "select * ", " from t_public_service where otherContext LIKE '%"+keyWord+"%' and areaCode = '"+code+"'");
			}
			else{
				return TPublicService.dao.paginate(currPage, pageSize, "select * ", " from t_public_service where isPass='"+state+"' and otherContext LIKE '%"+keyWord+"%' and areaCode = '"+code+"' ");
			}
		}
		else{
			if(state==""){
				return TPublicService.dao.paginate(currPage, pageSize, "select * ", " from t_public_service where otherContext LIKE '%"+keyWord+"%' and areaCode = '"+code+"'   ORDER BY createTime");
			}
			else{
				return TPublicService.dao.paginate(currPage, pageSize, "select * ", " from t_public_service where isPass='"+state+"' and otherContext LIKE '%"+keyWord+"%' and areaCode = '"+code+"'  ORDER BY createTime");
			}
		}
		
	}
	
	
	public Page<TPublicService> getImPage(Integer currPage, Integer pageSize, String state, String createTime, String keyWord, String code, Integer leavl) {
		if(createTime==""){
			if(state==""){
				return TPublicService.dao.paginate(currPage, pageSize, "select * ", " from t_public_service where otherContext LIKE '%"+keyWord+"%' and areaCode like '"+code+"%'");// and leavl = '"+leavl+"' ");
			}
			else{
				return TPublicService.dao.paginate(currPage, pageSize, "select * ", " from t_public_service where isPass='"+state+"' and otherContext LIKE '%"+keyWord+"%' and areaCode like '"+code+"%'");// and leavl = '"+leavl+"' ");
			}
		}
		else{
			if(state==""){
				return TPublicService.dao.paginate(currPage, pageSize, "select * ", " from t_public_service where otherContext LIKE '%"+keyWord+"%' and areaCode like '"+code+"%' ORDER BY createTime");// and leavl = '"+leavl+"'   ORDER BY createTime");
			}
			else{
				return TPublicService.dao.paginate(currPage, pageSize, "select * ", " from t_public_service where isPass='"+state+"' and otherContext LIKE '%"+keyWord+"%' and areaCode like '"+code+"%' ORDER BY createTime");// and leavl = '"+leavl+"'   ORDER BY createTime");
			}
		}
	}

	/***
	 * 删除
	 * @param ids
	 */
	@Before(Tx.class)
	public void deleteByIds(String ids){
		String idarr[] = ids.split(",");
    	for(String id : idarr){
    		TPublicService publicService = TPublicService.dao.findById(id);
    		publicService.delete();
    	}
	}
}
